package com.facebook;

public enum FacebookRequestError$Category
{
    AUTHENTICATION_REOPEN_SESSION("AUTHENTICATION_REOPEN_SESSION", 1), 
    AUTHENTICATION_RETRY("AUTHENTICATION_RETRY", 0), 
    BAD_REQUEST("BAD_REQUEST", 6), 
    CLIENT("CLIENT", 7), 
    OTHER("OTHER", 5), 
    PERMISSION("PERMISSION", 2), 
    SERVER("SERVER", 3), 
    THROTTLING("THROTTLING", 4);
}
